### ISSUE TITLE
Query parameter parsing does not allow plus symbols

### ISSUE THREAD

**Issue by fidian** [andrasq/node-qhttp#1]
`http_parse_query`, when given a string like "a+b%20c" will decode it as "a+b%20c". In the query string, a plus symbol is a shorthand for a space. More information on [StackOverflow](https://stackoverflow.com/questions/1005676/urls-and-plus-signs#answer-40292260).

To be fair, I don't know if the fix should go into this library or restiq, which is what I am using.

Would you be willing to make an update so that the parameters in the query string are modified to replace '+' with %20, then run the whole string through decodeURI? I was thinking it could be added to lib/http_parse_query.js.

    function decodeURI( str ) {
        try { return decodeURIComponent(str.replace(/\+/g, '%20'); }
        catch (err) { return str; }
    }

**Comment by andrasq** [comment]
hmm, that does indeed seem broken, query parsing should undo the URI encoding.  I'll look at it.

**Comment by andrasq** [comment]
fixed in qhttp@0.6.1 and restiq@0.9.2; urldecode now decodes + into spaces

The issue was that qhttp relied on `decodeURI` to decode the url encoding, but decodeURI and decodeURIComponent do not convert `+` to `' '` space.  Other languages eg php do, and `urldecode` is patterned after the php function by the same name.

**Comment by andrasq** [comment]
@fidian try restiq@0.9.2; see above
